jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Ensure Gradle Wrapper has execute permissions
    - name: Set execute permission for Gradle Wrapper
      run: chmod +x ./music-library/gradlew

    # Cache Gradle dependencies to speed up builds
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle Wrapper
      run: ./music-library/gradlew build

    - name: Run Tests
      run: ./music-library/gradlew test
